### PR TITLE
set appveyor

### PR DESCRIPTION
**Pull request by SummerSun**
Initiate the appveyor.yml file towards master branch to pull and process content to content repo.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@SummerSun__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (qisun). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by balajikris** [comment]
Not sure I understand what the purpose of this PR is or what it does. I have emailed the author seeking clarification.

**Comment by SummerSun** [comment]
Not sure if I check the correct email address but I did not get the email.
This PR is going to set the CI project to monitor, pull content to content repo for OPS build and publish.
@bradygaster could you please help explain details to production team? Thank you.

**Comment by balajikris** [comment]
Interesting, I emailed `qisun@microsoft.com` as AzureBot above figured was your email. @bradygaster - could you please explain to me in a little more detail about this effort? Adding you as a reviewer, if you could take a look. Thanks.

**Comment by balajikris** [comment]
ping.

**Comment by amarzavery** [comment]
@balajikris - They are setting up this bot so that they can push content to docs.microsoft.com website.

**Pull request merged**
