### PR TITLE
VM list-ip-address command.

### PR DESCRIPTION
**Pull request by shraddhaagrawal**
The content to be added to Changelog is as follows:
Closed all comments of PR https://github.com/Azure/azure-xplat-cli/pull/2968

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@shraddhaagrawal__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by shraddhaagrawal** [comment]
@huangpf  @haocs 
Please check

**Comment by huangpf** [comment]
LGTM

**Comment by haocs** [comment]
@shraddhaagrawal @huangpf 
Looks good! Thank you!

**Pull request merged**
