### PR TITLE
Arm app gw show

### PR DESCRIPTION
**Pull request by MikhailTryakhov**
The content to be added to Changelog is as follows:
* Reworked application gateway show command - separated json format

### CODE REVIEW

**Comment by amarzavery** [comment]
@MikhailTryakhov - Please resolve merge conflicts

**Comment by amarzavery** [comment]
@MikhailTryakhov - Please resolve merge conflicts

**Comment by amarzavery** [comment]
@MikhailTryakhov - We will be having a hot fix release today. Can you please resolve the merge conflicts and get the CI passing?

**Comment by MikhailTryakhov** [comment]
Thanks @amarzavery 
would be ready for 2 hours

**Comment by MikhailTryakhov** [comment]
@amarzavery done. sorry for delay

**Pull request merged**
