### PR TITLE
fix network vnet delete when there is only one network

### PR DESCRIPTION
**Pull request by freedev**
the command network vnet delete network-name does not work when there is only one existing network

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@freedev__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by romangromov** [comment]
@freedev use `!==` instead

**Comment by yugangw-msft** [comment]
The return value of  "indexOfCaseIgnore" looks rather odd that returns "null" if not found. Should have been '-1'

**Comment by freedev** [comment]
I have done an extensive search on the entire code base, there are 32 occurrences of indexOfCaseIgnore, and almost in every case there is a check for null.
Please forgive me if this is a dumb question: I agree that null is an odd return value for a method like "indexOfCaseIgnore", but even if we change the code everywhere from null to -1, shouldn't all developers that right now use this method agree this change of behaviour?

**Comment by freedev** [comment]
@yugangw-msft please take a look at:
- lib/commands/asm/network/dnsServer._js [line 126]
This could be a latent bug.

**Comment by yugangw-msft** [comment]
@freedev yes that is bug.
Your PR has been merged. Feel free to work with Roman and submit a new PR to improve it

**Comment by romangromov** [comment]
@freedev @yugangw-msft I'm looking into this issue, will share update on this, thank you all guys

**Pull request merged**
