### PR TITLE
Update Compute Package Version

### PR DESCRIPTION
**Pull request by huangpf**
The content to be added to Changelog is as follows:
* Update Compute SDK Package to ```2.0.0-preview``` with new API version

### CODE REVIEW

**Comment by huangpf** [comment]
All tests passed locally, but failed here. Why?

```
...
  . arm appserviceplan delete should work: 274ms

  855 passing (11m)
  32 pending

End:3:31:22 PM
```

**Comment by huangpf** [comment]
@balajikris

**Comment by huangpf** [comment]
retest this please

**Comment by balajikris** [comment]
@huangpf - I think I've fixed the out-of-memory exception in tests with this PR: https://github.com/Azure/azure-xplat-cli/pull/3600 . Please get the latest changes from `dev` and retest.

**Comment by balajikris** [comment]
@huangpf - I wonder why you have to skip any iothub tests, as they're passing in `dev` branch. Could you explain?

**Comment by huangpf** [comment]
@balajikris It doesn't pass in my local run. I re-enable it for CI test now. Let's see if it passes.

**Comment by huangpf** [comment]
Setting this will make the test pass locally:
```
set AZURE_SUBSCRIPTION_ID=
```

**Comment by balajikris** [comment]
@huangpf - the trick is, if it isn't your test or if it isn't something that shouldn't be affected by your changes, just send a PR and see if the CI passes. If it does, lets not worry about local failures as your environment might not be set up for the entire suite. I suppose thats the best we can do when multiple teams work on the same project. Anyway, all good now 👍

**Pull request merged**
