### PR TITLE
Add CLI changes for validate migration apis

### PR DESCRIPTION
**Pull request by priydes**
The content to be added to Changelog is as follows:
* CLI commands for validate migration for Deployment, Virtual Network, and Storage from ASM to ARM
* Unit tests for new CLI commands
* Updated package.json to the latest version

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@priydes__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by amarzavery** [comment]
please add content to be added to the changelog in the PR description.

**Comment by huangpf** [comment]
LGTM.

**Comment by DeepakRajendranMsft** [comment]
LGTM

**Pull request merged**
