### PR TITLE
Urgent! Critical fix of issue with ID 6762945.

### PR DESCRIPTION
**Pull request by MikhailTryakhov**
The content to be added to Changelog is as follows:
* Added extra-validator for record set location (set default if it's empty)

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@MikhailTryakhov__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by MikhailTryakhov** [comment]
Hi guys
please try to merge this fix ASAP

**Comment by haocs** [comment]
@MikhailTryakhov - please re-target your PR to release branch over here https://github.com/Azure/azure-xplat-cli/tree/release-0.10.2

**Comment by MikhailTryakhov** [comment]
Created new [PR#2988](https://github.com/Azure/azure-xplat-cli/pull/2988) to specified branch

**Pull request closed without merging**
