### PR TITLE
[Do not merge]: touch a random file to trigger CI

### PR DESCRIPTION
**Pull request by yugangw-msft**
Open this PR to confirm an existing CI test flakiness

### CODE REVIEW

**Comment by yugangw-msft** [comment]
@balajikris, could you take a look the CI failure? Data lake tests are failing in current dev branch

**Comment by balajikris** [comment]
tagging @amarzavery as well.

**Comment by balajikris** [comment]
I wonder how [this build](https://travis-ci.org/Azure/azure-xplat-cli/builds/220517089) which ran 7 hours ago, passed cleanly. Is this an intermittent failure?

**Comment by MikhailTryakhov** [comment]
@balajikris @amarzavery Have the same problem: it fails on Travis, but works correct locally.
Commented out this test in my [PRs](https://github.com/Azure/azure-xplat-cli/pull/3527/files#diff-42bd6bf8546a99b64d7a566ff8204a5eR92)

Can we ping related commands to review it? Tried to rewrite recordings but it didn't fix it on Travis

**Comment by balajikris** [comment]
@amarzavery helped figure this out. Will send a PR. thanks everyone, for investigating.

**Pull request closed without merging**
