### PR TITLE
Bug fix and test improvement for command "azure vm enable-aem "

### PR DESCRIPTION
**Pull request by yuezh**
The content to be added to Changelog is as follows:
* Add more test for command "azure vm enable-aem "
* Fix storage account name case sensitive issue for command "azure vm enable-aem "

### CODE REVIEW

**Comment by amarzavery** [comment]
@yuezh - Please pull from upstream and merge conflicts.

**Comment by yuezh** [comment]
Ok. will do that.

**Comment by amarzavery** [comment]
@yuezh - Ping ???

**Comment by yuezh** [comment]
@amarzavery It seems more conflicts was happening in upstream. will merge again.

**Comment by yuezh** [comment]
The CI test failed with installing new npm. It seems to be a test issue. How could I retrigger the CI to re-run?

1614.33s$ npm install -g npm@1.4.23

162WARN engine npm@1.4.23: wanted: {"node":">=0.8","npm":"1"} (current: {"node":"4.2.4","npm":"2.14.12"})

163/home/travis/.nvm/versions/node/v4.2.4/bin/npm -> /home/travis/.nvm/versions/node/v4.2.4/lib/node_modules/npm/bin/npm-cli.js

164npm@1.4.23 /home/travis/.nvm/versions/node/v4.2.4/lib/node_modules/npm

165


install.21660.21s$ npm --version

1671.4.23

168


1691.54s$ npm install

170npm ERR! fetch failed https://registry.npmjs.org/through/-/through-2.3.4.tgz

**Comment by yuezh** [comment]
Close this one and reopen to trigger CI to rerun

**Pull request closed without merging**
