### PR TITLE
More disk & vm tests

### PR DESCRIPTION
**Pull request by huangpf**
The content to be added to Changelog is as follows:
* 
* 
*

### CODE REVIEW

**Comment by huangpf** [comment]
@amarzavery 
Tests are failing, but it shows ```All checks have passed``` ---
https://travis-ci.org/Azure/azure-xplat-cli/builds/199347632

99 passing (25s)
  1 pending
  2 failing
  1) cli site log config should allow setting everything with output as file:
     Uncaught Error: Nock: No match for HTTP request GET /8d57ddbd-c779-40ea-b660-1015f4bf027d/services/WebSpaces/LukaszPersonalResourceGroup-WestUSwebspace/sites?propertiesToInclude=repositoryuri%2Cpublishingpassword%2Cpublishingusername 
      at RequestOverrider.end (/home/travis/build/Azure/azure-xplat-cli/node_modules/nock/lib/request_overrider.js:159:13)
      at OverridenClientRequest.RequestOverrider.req.end (/home/travis/build/Azure/azure-xplat-cli/node_modules/nock/lib/request_overrider.js:104:7)
      at Request.end (/home/travis/build/Azure/azure-xplat-cli/node_modules/request/request.js:1397:14)
      at end (/home/travis/build/Azure/azure-xplat-cli/node_modules/request/request.js:567:14)
      at Immediate._onImmediate (/home/travis/build/Azure/azure-xplat-cli/node_modules/request/request.js:581:7)
      at processImmediate [as _immediateCallback] (timers.js:396:17)
  
  2) cli site log "after each" hook:
     Uncaught Error: Nock: No match for HTTP request GET /8d57ddbd-c779-40ea-b660-1015f4bf027d/services/WebSpaces/LukaszPersonalResourceGroup-WestUSwebspace/sites?propertiesToInclude=repositoryuri%2Cpublishingpassword%2Cpublishingusername

**Comment by huangpf** [comment]
Include: https://github.com/Azure/azure-xplat-cli/pull/3483

**Comment by huangpf** [comment]
@amarzavery @balajikris Could you please help review & merge our last test PR? Thanks!

**Comment by balajikris** [comment]
I have noticed this before. These two asm tests have been failing for a long time. The reason CI shows all tests have passed is because mocha returns exit code 0, which is a bug. This should go away when we upgrade mocha and its work in progress. 
Short answer, for purposes of htis PR, ignore the two failures. you're good here.

**Comment by huangpf** [comment]
Thanks @balajikris & @amarzavery 

Could you please help review & merge? So that we can confirm with the team that it's done, and then move forward. Thanks.

**Pull request merged**
