### PR TITLE
Resolved issue with ARM VM Show method

### PR DESCRIPTION
**Pull request by MikhailTryakhov**
The content to be added to Changelog is as follows:
* Changed show vm functionalirt: throw error instead of warning if incorrect name of VM was entered

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@MikhailTryakhov__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by haocs** [comment]
@MikhailTryakhov - This PR looks good. It will be great if you could update the 'vm show' testing accordingly as well.

**Comment by MikhailTryakhov** [comment]
HI @haocs 
will discuss about it - assume we should work on mock tests a lot because they're too simple and can not handle a lot of potentially problem bugs.
For example, a lot of associated scripts can fail after simple property renaming. No tests can handle it now.

**Comment by haocs** [comment]
@MikhailTryakhov - Yes, totally agree. We can do this after this release(next Thursday). I assume there will be many changes.

**Comment by MikhailTryakhov** [comment]
@haocs can we sync up about test cases which can help us close most of possible issues?
- Test incorrect values ('it should not pass' tests)
- Try to find items, which don't exist
- Test duplicated items

What do you think, which other cases can be helpful in tests? 
Feel free to ping me to make a call

**Pull request merged**
