### PR TITLE
Reworked local gateways.

### PR DESCRIPTION
**Pull request by MikhailTryakhov**
The content to be added to Changelog is as follows:
* Fixed issue [#3351](https://github.com/Azure/azure-xplat-cli/issues/3351)

### CODE REVIEW

**Comment by balajikris** [comment]
Hey @MikhailTryakhov - there seem to be test failures with this PR. feel free to ping me after you fix them and I'll take a look at the changes. Thanks.

**Comment by MikhailTryakhov** [comment]
Yeah, @balajikris, I'm working on it.
This is generated code and we publish it the first time for such cases - need to fix few more issues

**Comment by MikhailTryakhov** [comment]
@balajikris  small holiday on our side - it's fixed and ready for merge

**Comment by amarzavery** [comment]
@MikhailTryakhov - Please resolve merge conflicts.

**Comment by MikhailTryakhov** [comment]
@amarzavery conflicts resolved

**Pull request merged**
