### PR TITLE
Renamed chef-service-interval option name to chef-daemon-interval

### PR DESCRIPTION
**Pull request by piyushawasthi**
- Renamed chef-service-interval option name to chef-daemon-interval.
- Fixed ASM and ARM test cases.

### CODE REVIEW

**Comment by NimishaS** [comment]
Testing the PR.

**Comment by balajikris** [comment]
@piyushawasthi @NimishaS  - thanks for the PR! can one of you fix the merge conflicts and update the PR? Thanks.

**Comment by piyushawasthi** [comment]
@balajikris, @NimishaS  - Fixed merge conflicts, update recording, update tests and verify all changes manually as well.

**Comment by balajikris** [comment]
Thanks everyone!

**Pull request merged**
