### PR TITLE
Arm lb inbound nat pool test cases added

### PR DESCRIPTION
**Pull request by babumuralidharan**
This is a test PR that contains lb inbound nat pool tests added with recordings.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@babumuralidharan__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (v-bamura). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by amarzavery** [comment]
@babumuralidharan - Please send a PR to the release-0.9.10 branch for it to be included in this release.

**Comment by babumuralidharan** [comment]
@amarzavery sent a PR to release branch as well. Thanks

**Comment by amarzavery** [comment]
Closing this because #2158 has been merged in tot he release branch

**Pull request closed without merging**
