### PR TITLE
Improved Network DNS Zone Import's data validation

### PR DESCRIPTION
**Pull request by number213**
* Added validation for record set names
* Added code to trim tokens like `[AGE:xxxxxx]` that make DNS zone list input invalid
* Improved `dns zone import` progress' output
* Re-recorded unit tests

The content to be added to Changelog is as follows:
* Network
  * DNS Zone Import's data validation is improved

### CODE REVIEW

**Comment by MikhailTryakhov** [comment]
@number213 has it been tested by Jonathan?

**Comment by MikhailTryakhov** [comment]
LGTM

**Comment by number213** [comment]
@MikhailTryakhov I've uploaded changes to his VM but he hasn't replied to me yet. I've pinged him today.

**Comment by jtuliani** [comment]
I tried the shared VM, everything worked perfectly! Please ship it :)

**Comment by balajikris** [comment]
Thanks everyone. Thanks @jtuliani and @MikhailTryakhov for testing and reviewing the changes!

**Pull request merged**
