### PR TITLE
Added NoSSHEndpoint support

### PR DESCRIPTION
**Pull request by arjanschaaf**
I mostly create ssh password-less VM's in Virtual Networks. So I don't have the need for a public ssh endpoint, as we ssh into the machines from inside the virtual network.
The current CLI implementation requires a public ssh endpoint when starting a VM with the --no-ssh-passsword argument. The Azure Powershell does provide a -NoSSHEndpoint option for Linux Provisioning Configs.

I'll created this pull request to enable the same feature is in the Powershell implementation.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@arjanschaaf__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by yugangw-msft** [comment]
@anuchandy , could you please take a look this PR

**Comment by arjanschaaf** [comment]
Hi @yugangw-msft & @anuchandy 

Any thoughts on incorporating this pull request?

Kind regards,
Arjan

**Comment by anuchandy** [comment]
@arjanschaaf Thank you, this looks good to me.

@amarzavery fyi

**Comment by tsaarni** [comment]
Sorry for spamming above. Unfortunately I was not aware that mentions in fork generate messages into forked repo.

@arjanschaaf can you check if change in 09f9a6d519b0ef427e16301d3fdc910633da9ab0 reflects what you intended originally?

**Comment by arjanschaaf** [comment]
LGTM @tsaarni

**Pull request merged**
