### PR TITLE
ARM DNS services improved

### PR DESCRIPTION
**Pull request by MikhailTryakhov**
The content to be added to Changelog is as follows:
* Added option --quiet in the ```dns record-set add-record``` command to make CNAME records corrections available for scripting
* added a chance in the ```dns record-set list``` command to filter record sets by type without setting option name
* Fixed ```dns records-set delete-record``` ```--type``` option description
* Fixed ```dns record-set``` commands case-sensitive ```--type``` option issue
* Corrected record-set show command displaying format
* Added ```--keep-empty-record-set``` option to remove record saving empty record set.
* Added default functionality to remove record set is last record was deleted

### CODE REVIEW

**Comment by balajikris** [comment]
hey @MikhailTryakhov : let me know if this is ready and if you'd like me to review.

**Comment by MikhailTryakhov** [comment]
Hi @balajikris 
thanks, it's ready for review

**Comment by MikhailTryakhov** [comment]
@balajikris  could you please make a review?

**Comment by balajikris** [comment]
Noted, I've been out of office. Will review and merge at the earliest.

**Comment by balajikris** [comment]
Thanks @MikhailTryakhov !

**Pull request merged**
