### PR TITLE
Use formatOutput for deployment create/show to fix --json output issue

### PR DESCRIPTION
**Pull request by vivsriaus**

### CODE REVIEW

**Comment by amarzavery** [comment]
@vivsriaus - Travis CI failed due to jshint issue.

```
<?xml version="1.0" encoding="utf-8"?>
<jslint>
	<file name="lib/commands/arm/group/group.deployment._js">
		<issue line="108" char="31" reason="&apos;outputData&apos; is not defined." evidence="            displayDeployment(outputData, resourceGroup, true, log);" severity="W" />
		<issue line="184" char="31" reason="&apos;outputData&apos; is not defined." evidence="            displayDeployment(outputData, resourceGroup, true, log);" severity="W" />
	</file>
</jslint>
```

**Comment by vivsriaus** [comment]
@amarzavery fixed

**Comment by amarzavery** [comment]
Can you modify the current test to parse the json output and verify some values like resource groupname, deployment name, etc. that will make sure we don't regress ...

Thanks,
Amar Zavery

On Feb 16, 2016, at 4:07 PM, "vivsriaus" <notifications@github.com<mailto:notifications@github.com>> wrote:


@amarzavery<https://github.com/amarzavery> fixed

-

**Comment by vivsriaus** [comment]
@amarzavery Thanks. I've updated a couple of tests to do exactly that. :)

**Comment by amarzavery** [comment]
@vivsriaus - You are awesome !

**Pull request merged**
