### PR TITLE
Add disk/snapshot/vmss/availset/vm-convert & baseline VM tests

### PR DESCRIPTION
**Pull request by huangpf**
The content to be added to Changelog is as follows:
* 
* 
*

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@huangpf__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by huangpf** [comment]
@amarzavery Why suddenly I'm required for CLA? :-)

**Comment by amarzavery** [comment]
Looks like a github bot issue. Don't worry it did the same thing to me.

**Comment by huangpf** [comment]
```
@huangpf huangpf closed this 41 seconds ago
 @huangpf huangpf reopened this 40 seconds ago
 @azurecla azurecla added cla-not-required and removed cla-required labels 14 seconds ago
```

lol...

**Comment by huangpf** [comment]
@amarzavery @balajikris Could you please help review & merge this PR for tests?

It includes commits from:
https://github.com/Azure/azure-xplat-cli/pull/3480
https://github.com/Azure/azure-xplat-cli/pull/3478

**Pull request merged**
