### PR TITLE
Add support for creating ExpressRoute VPN gateways

### PR DESCRIPTION
**Pull request by atoakley**
Fix for #2686 

- Added gatewayType parameter to VPN gateway create method
- Fixed incorrect parameter description for VPN gateway create method

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@atoakley__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (anoakley). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by romangromov** [comment]
@atoakley this should be covered with related test case. 

I sugget to modify test named `create should create vpn gateway` from `\test\commands\arm\network\arm.network.vpn-gateway-tests.js` to handle new option `-gateway-type`

Also we need to add "Gateway Type" column to `azure network vpn-gateway list` command.

Hope this helps

**Comment by atoakley** [comment]
@romangromov I will try to update the tests today.

The "Gateway Type" column is already returned in the ```azure network vpn-gateway list``` command.  I tested it before I submitted my PR and it returns "ExpressRoute" for the appropriate gateways so I think this is good.

**Comment by romangromov** [comment]
@atoakley let me take care of this PR and finish task

**Pull request closed without merging**
