### PR TITLE
Fixed link for automation auth

### PR DESCRIPTION
**Pull request by tstringer**
The content to be added to Changelog is as follows:
* The link was broken linking to the `azure-sdk-for-node` repo documentation for creating a principal

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@tstringer__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by amarzavery** [comment]
@romangromov @MikhailTryakhov @huangpf - All the PRs are failing due to Travis CI test failures in compute and network land. Can you please take a look at this https://travis-ci.org/Azure/azure-xplat-cli/jobs/129984865.

This is happening this and the CDN PR. The [initial review] PR need not be considered for now.

**Comment by romangromov** [comment]
@amarzavery the reason of test cases failure is new API version propagated by  `azure-arm-network: 0.13.2` package. That means `vm ` tests recordings needs to be updated

**Comment by nbikhchandani** [comment]
Hi @amarzavery, looks like the checkin failed due to vm test recordings, which my changeset doesn't touch. Could you please take a look. Thanks.

**Comment by amarzavery** [comment]
@huangpf - Can you record or update the api-version in the test recordings for the updated tests?

**Comment by huangpf** [comment]
I’m not sure why the task would suddenly be on me. First of all, the test runs fine without the new PR, and secondly the convention is “who breaks it fixes it”, meaning that the PR owner would need to do it according to your advice on how to utilize the test framework.

**Comment by huangpf** [comment]
BTW, according to the logs, the ```azure-arm-network``` update was done by @romangromov. Why did it pass the check-in tests then but not now?

**Comment by amarzavery** [comment]
@huangpf - You are correct. Since network trumped over the api-version its their responsibility to re-record those tests that are failing due to network api-version change.

@romangromov - Please update the test recordings

**Comment by romangromov** [comment]
sure, @amarzavery recordings updated

**Pull request merged**
