### PR TITLE
correct CN for the default docker cert

### PR DESCRIPTION
**Pull request by waitingkuo**
Modify the CN for the default docker cert from * to *.cloudapp.net
It's the implementation of #1523 

Signed-off-by: Wei-Ting Kuo <waitingkuo0527@gmail.com>

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@waitingkuo__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
Please fix the build breaks. 
Please update this PR by EOW. We will close it otherwise.

**Comment by waitingkuo** [comment]
Updated

**Comment by yugangw-msft** [comment]
@anuchandy , please take a look.

**Comment by anuchandy** [comment]
Looks good to me.. @hopetobelievein any feedback?

**Comment by hopetobelievein** [comment]
@anuchandy looks good.

**Comment by yugangw-msft** [comment]
i will port this change to dev branch. We will make dev branch to be the default moving forward

**Comment by yugangw-msft** [comment]
#1662

**Pull request closed without merging**
