### PR TITLE
Added Disabled Rule Groups and Path Based Routing support to AppGw & replaced some tests with autogenerated ones

### PR DESCRIPTION
**Pull request by number213**
* Updated azure-arm-network's version in package.json
* Added support for disabled rule groups to Application Gateway's WAF Config
* Added support for path based routing to Application Gateway's Request Routing Rules
* Replaced tests for Application Gateways, Load Balancers, Network Security Groups, Route Tables and Local Network Gateways with autogenerated ones

The content to be added to Changelog is as follows:
* Network
    * Application Gateway
        * Added support for Disabled Rule Groups to WAF Config
        * Added support for Path Based Routing to Request Routing Rules

### CODE REVIEW

**Comment by number213** [comment]
Hey @balajikris, everything's ready for PR review

**Comment by DeepakRajendranMsft** [comment]
@balajikris, please take a look this PR

**Comment by balajikris** [comment]
@number213  - What part of this is hand-written and what is auto-gen'd? 
@DeepakRajendranMsft - Feel free to review if you wish. I'll be looking in a bit.

**Comment by number213** [comment]
@balajikris 

Autogen'd:

- ApplicationGateways-requestRoutingRules._js
- ApplicationGateways-webApplicationFirewallConfiguration._js
- applicationGateways._js
- All changed tests except arm.network.application-gateway-non-gen-tests.js

Handwritten:
- appGateway._js
- network._js

**Comment by balajikris** [comment]
Thanks for the list. Reviewing 60k lines in a PR is next to impossible. Here is what we'll do to manage changes like this - 

1. create smaller, more manageable PRs
2. If for some reason, that's not possible, then at least break them down into many smaller commits that are manageable.
3. I've already reviewed and provided feedback for code that is autogen'd. I'm now comfortable with the pattern it uses to generate commands. So, I won't be reviewing auto generated code. But, I'll be interested in reviewing anything that's handwritten. So have separate commits for autogenerated code and manually written code, please do not mix them in the same commit. Then, provide us with a list of commits or files that are handwritten.
4. tests should pass, I think we'll agree that's a given :)

Does this sound reasonable?

**Comment by number213** [comment]
@balajikris ok, I'll do that

**Comment by balajikris** [comment]
@number213 -- Thanks! Ping me once you've updated the PR.

**Comment by number213** [comment]
Hi, @balajikris, I opened PR with new API for AppGw (https://github.com/Azure/azure-xplat-cli/pull/3604). This one is getting messy so I'll close it.
I'll upload autogenerated tests after we bump Network's package version to 1.0.0-preview so I won't have to re-record them later. I think that's OK since we don't really need them for release.

**Comment by balajikris** [comment]
That sounds reasonable @number213 . Go for it. 👍

**Pull request closed without merging**
