### PR TITLE
Reworked unit tests to common code style.

### PR DESCRIPTION
**Pull request by MikhailTryakhov**
Corrected stopAppGateway method.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@MikhailTryakhov__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by amarzavery** [comment]
@MikhailTryakhov - I am closing this PR. I have fixed the issues with failing CI in this PR #2744 .

You can look at this specific commit to see the changes made to network tests and the infrastructure.
https://github.com/Azure/azure-xplat-cli/pull/2744/commits/ffd0cc3c45ea407032d7b44b0de239c3f03f998f

**Comment by MikhailTryakhov** [comment]
Hi @amarzavery but there there some fixes which were not added to specified files.
Can you please review new PR https://github.com/Azure/azure-xplat-cli/pull/2746 (can't reopen this one)

**Comment by amarzavery** [comment]
Mikhail please send the pr to release branch and not to the dev branch. Make sure the CI passes. I had to get it working last night. Please make sure that all the changes are done at once.

Thanks,
Amar Zavery

On Apr 13, 2016, at 2:46 AM, "Mikhail" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @amarzavery<https://github.com/amarzavery> but there there some fixes which were not added to specified files.
Can you please review new PR #2746<https://github.com/Azure/azure-xplat-cli/pull/2746> (can't reopen this one)

-

**Pull request closed without merging**
