### PR TITLE
azure-arm-network update

### PR DESCRIPTION
**Pull request by number213**
Updated azure-arm-network to 1.4.0-preview (it isn't published yet)

* Updated code for AppGw's SslPolicy (lib/commands/arm/network/applicationGateway.helper._js)
* Updated VMSS tests, usage test & recordings

### CODE REVIEW

**Comment by balajikris** [comment]
@number213 -- can you please correct the version number and have the CI passing?

**Comment by balajikris** [comment]
So, applicationGateway.helper._js and package.json are the only handwritten files? If so, LGTM after CI passes

**Comment by balajikris** [comment]
@number213 -- see above.

**Comment by number213** [comment]
@balajikris thanks!

**Pull request merged**
