### PR TITLE
Update kuduscript

### PR DESCRIPTION
**Pull request by amitapl**
Fix python tests

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@amitapl__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (amitap). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by amarzavery** [comment]
@amitapl - nock recording files for this test?

**Comment by amarzavery** [comment]
@amitapl - At the same time we are moving to a better test recording infrastructure (one recording file per test). Please take a look at this PR https://github.com/Azure/azure-xplat-cli/pull/1642 .

Can you record your tests after this PR is merged, so the tests can be run mocked on CI server?

**Comment by amitapl** [comment]
Actually there is no need as these tests are not using any network :) (they generate scripts)

**Comment by amarzavery** [comment]
Ah I see. then it should be fine :)

**Pull request merged**
