### PR TITLE
Add optional environment to specify resource group.

### PR DESCRIPTION
**Pull request by karlaugsten**
Add optional environment variable AZURE_ARM_TEST_RESOURCE_GROUP in keyvault tests to specify resource group.

- Currently no other tests use the AZURE_ARM_TEST_RESOURCE_GROUP variable.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@karlaugsten__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by yugangw-msft** [comment]
@msfcolombo , please take a look. The change looks reasonable, even it touches the recording file, but the change will persist even when you re-record in future

**Comment by msfcolombo** [comment]
@yugangw-msft, the change looks good, I review with @karlaugsten before he submitted. The rationale is to evolve towards allowing full parallel execution of live tests (so names cannot be reused). We manually changed the recordings because it's not using the default value defined in the test itself. We could do re-record but then the delta would be unnecessarily big. Thanks for calling my attention.

**Comment by yugangw-msft** [comment]
sounds good

**Pull request merged**
