### PR TITLE
Update Linux distribution SKUs to the latest

### PR DESCRIPTION
**Pull request by szarkos**
CentOS -> 7.3
RHEL -> 7.3
openSUSE -> 42.1
SLES -> 12-SP2
Ubuntu -> 16.04-LTS

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@szarkos__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (szark). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by balajikris** [comment]
@szarkos : thank you for the PR. It seems these changes are causing some legit test failures, would you be willing to investigate and make the CI run pass?

**Comment by szarkos** [comment]
I have no idea what's failing.  I do see the error "[Error: The access token is invalid.]".  The changes I made are fairly trivial and should be correct.

**Comment by balajikris** [comment]
CI logs from https://travis-ci.org/Azure/azure-xplat-cli/builds/195323098

It appears 5 arm tests are failing. It was the same set of failures in the initial attempt as well (you could verify that by clicking the red x mark next to the first commit). 
Given the consistency of the failures in this PR and the robustness of our suite (we do not have any known flaky tests), I'm not comfortable merging this change, until we better understand why tests are consistently failing with this change.

**Logs:**
~~~
  733 passing (6m)
  32 pending
  5 failing
  1) arm compute vm quick create with non-existing group should pass:
     Uncaught Error: Nock: No match for HTTP request PUT /subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTestVMQCreate7290/providers/Microsoft.Storage/storageAccounts/clisto222512201vm14115?api-version=2016-01-01 {"sku":{"name":"Standard_LRS"},"kind":"Storage","location":"westus"}
      at RequestOverrider.end (/home/travis/build/Azure/azure-xplat-cli/node_modules/nock/lib/request_overrider.js:159:13)
      at OverridenClientRequest.RequestOverrider.req.end (/home/travis/build/Azure/azure-xplat-cli/node_modules/nock/lib/request_overrider.js:104:7)
      at Request.end (/home/travis/build/Azure/azure-xplat-cli/node_modules/request/request.js:1397:14)
      at end (/home/travis/build/Azure/azure-xplat-cli/node_modules/request/request.js:554:16)
      at Immediate._onImmediate (/home/travis/build/Azure/azure-xplat-cli/node_modules/request/request.js:581:7)
      at processImmediate [as _immediateCallback] (timers.js:396:17)
  
  2) arm compute vm vm secret random add should fail:
      + expected - actual
      +0
      -1
      
      at Assertion.prop.(anonymous function) (/home/travis/build/Azure/azure-xplat-cli/node_modules/should/lib/should.js:61:14)
      at /home/travis/build/Azure/azure-xplat-cli/test/commands/arm/vm/arm.vm-quick-create-tests.js:102:42
      at /home/travis/build/Azure/azure-xplat-cli/test/util/util.js:206:7
      at /home/travis/build/Azure/azure-xplat-cli/test/framework/cli-test.js:204:7
      at /home/travis/build/Azure/azure-xplat-cli/test/framework/cli-executor.js:56:14
      at /home/travis/build/Azure/azure-xplat-cli/node_modules/underscore/underscore.js:683:19
      at process.<anonymous> (/home/travis/build/Azure/azure-xplat-cli/test/framework/cli-executor.js:68:7)
      at Function.invoke (/home/travis/build/Azure/azure-xplat-cli/node_modules/sinon/lib/sinon/spy.js:176:59)
      at process.proxy (eval at createProxy (/home/travis/build/Azure/azure-xplat-cli/node_modules/sinon/lib/sinon/spy.js:81:86), <anonymous>:1:35)
      at AzureCli.cli.__proto__.exitProcess (/home/travis/build/Azure/azure-xplat-cli/test/framework/cli-executor.js:74:63)
      at AzureCli._.extend.exit (/home/travis/build/Azure/azure-xplat-cli/lib/cli.js:162:10)
      at /home/travis/build/Azure/azure-xplat-cli/lib/cli.js:275:18
      at Object.exports.onError (/home/travis/build/Azure/azure-xplat-cli/lib/util/telemetry.js:271:5)
      at callback (/home/travis/build/Azure/azure-xplat-cli/lib/cli.js:265:21)
      at ___ (/home/travis/build/Azure/azure-xplat-cli/node_modules/streamline/lib/callbacks/runtime.js:108:14)
      at ___ (/home/travis/build/Azure/azure-xplat-cli/node_modules/streamline/lib/callbacks/runtime.js:108:14)
      at ___ (/home/travis/build/Azure/azure-xplat-cli/lib/commands/arm/vm/virtualMachine._js:640:17)
      at __tryCatch (/home/travis/build/Azure/azure-xplat-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)
      at ___ (/home/travis/build/Azure/azure-xplat-cli/lib/commands/arm/vm/virtualMachine._js:636:13)
      at __$createOrUpdateVM__14 (/home/travis/build/Azure/azure-xplat-cli/lib/commands/arm/vm/virtualMachine._js:633:15)
      at __tryCatch (/home/travis/build/Azure/azure-xplat-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)
      at ___ (/home/travis/build/Azure/azure-xplat-cli/lib/commands/arm/vm/virtualMachine._js:631:13)
      at ___ (/home/travis/build/Azure/azure-xplat-cli/lib/commands/arm/vm/virtualMachine._js:635:13)
      at ___ (/home/travis/build/Azure/azure-xplat-cli/node_modules/streamline/lib/callbacks/runtime.js:108:14)
      at /home/travis/build/Azure/azure-xplat-cli/node_modules/azure-arm-compute/lib/operations/virtualMachines.js:532:21
      at /home/travis/build/Azure/azure-xplat-cli/node_modules/azure-arm-compute/lib/operations/virtualMachines.js:899:14
      at retryCallback (/home/travis/build/Azure/azure-xplat-cli/node_modules/ms-rest/lib/filters/exponentialRetryPolicyFilter.js:140:9)
      at handleRedirect (/home/travis/build/Azure/azure-xplat-cli/node_modules/ms-rest/lib/filters/redirectFilter.js:36:9)
      at /home/travis/build/Azure/azure-xplat-cli/lib/util/utils.js:605:7
      at handleRedirect (/home/travis/build/Azure/azure-xplat-cli/lib/util/utils.js:582:9)
      at /home/travis/build/Azure/azure-xplat-cli/lib/util/logging.js:339:7
      at Request._callback (/home/travis/build/Azure/azure-xplat-cli/node_modules/ms-rest/lib/requestPipeline.js:125:16)
      at Request.self.callback (/home/travis/build/Azure/azure-xplat-cli/node_modules/request/request.js:187:22)
      at emitTwo (events.js:87:13)
      at Request.emit (events.js:172:7)
      at Request.<anonymous> (/home/travis/build/Azure/azure-xplat-cli/node_modules/request/request.js:1044:10)
      at emitOne (events.js:82:20)
      at Request.emit (events.js:169:7)
      at OutgoingMessage.<anonymous> (/home/travis/build/Azure/azure-xplat-cli/node_modules/request/request.js:965:12)
      at emitNone (events.js:72:20)
      at OutgoingMessage.emit (events.js:166:7)
      at /home/travis/build/Azure/azure-xplat-cli/node_modules/nock/lib/request_overrider.js:229:18
      at /home/travis/build/Azure/azure-xplat-cli/node_modules/nock/lib/request_overrider.js:236:21
      at nextTickCallbackWith0Args (node.js:436:9)
      at process._tickCallback (node.js:365:13)
  
  3) arm compute vmss vmss quick-create should pass:
     Uncaught Error: Nock: No match for HTTP request GET /subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/resourceGroups/xplatTestVMSSCreate4329/providers/Microsoft.Network/networkInterfaces/xplat-south-1083776704-nic?api-version=2016-09-01 
      at RequestOverrider.end (/home/travis/build/Azure/azure-xplat-cli/node_modules/nock/lib/request_overrider.js:159:13)
      at OverridenClientRequest.RequestOverrider.req.end (/home/travis/build/Azure/azure-xplat-cli/node_modules/nock/lib/request_overrider.js:104:7)
      at Request.end (/home/travis/build/Azure/azure-xplat-cli/node_modules/request/request.js:1397:14)
      at end (/home/travis/build/Azure/azure-xplat-cli/node_modules/request/request.js:567:14)
      at Immediate._onImmediate (/home/travis/build/Azure/azure-xplat-cli/node_modules/request/request.js:581:7)
      at processImmediate [as _immediateCallback] (timers.js:396:17)
  
  4) arm compute vmss vmssvm operations should pass:
     Uncaught Error: Nock: No match for HTTP request GET /subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/resourcegroups/xplatTestVMSSCreate4329?api-version=2016-09-01 
      at RequestOverrider.end (/home/travis/build/Azure/azure-xplat-cli/node_modules/nock/lib/request_overrider.js:159:13)
      at OverridenClientRequest.RequestOverrider.req.end (/home/travis/build/Azure/azure-xplat-cli/node_modules/nock/lib/request_overrider.js:104:7)
      at Request.end (/home/travis/build/Azure/azure-xplat-cli/node_modules/request/request.js:1397:14)
      at end (/home/travis/build/Azure/azure-xplat-cli/node_modules/request/request.js:567:14)
      at Immediate._onImmediate (/home/travis/build/Azure/azure-xplat-cli/node_modules/request/request.js:581:7)
      at processImmediate [as _immediateCallback] (timers.js:396:17)
  
  5) arm compute vmss vmss update instances should pass:
      + expected - actual
      +0
      -1
      
      at Assertion.prop.(anonymous function) (/home/travis/build/Azure/azure-xplat-cli/node_modules/should/lib/should.js:61:14)
      at /home/travis/build/Azure/azure-xplat-cli/test/commands/arm/vmss/arm.vmss-create-tests.js:141:46
      at /home/travis/build/Azure/azure-xplat-cli/test/util/util.js:206:7
      at /home/travis/build/Azure/azure-xplat-cli/test/framework/cli-test.js:204:7
      at /home/travis/build/Azure/azure-xplat-cli/test/framework/cli-executor.js:56:14
      at /home/travis/build/Azure/azure-xplat-cli/node_modules/underscore/underscore.js:683:19
      at process.<anonymous> (/home/travis/build/Azure/azure-xplat-cli/test/framework/cli-executor.js:68:7)
      at Function.invoke (/home/travis/build/Azure/azure-xplat-cli/node_modules/sinon/lib/sinon/spy.js:176:59)
      at process.proxy (eval at createProxy (/home/travis/build/Azure/azure-xplat-cli/node_modules/sinon/lib/sinon/spy.js:81:86), <anonymous>:1:35)
      at AzureCli.cli.__proto__.exitProcess (/home/travis/build/Azure/azure-xplat-cli/test/framework/cli-executor.js:74:63)
      at AzureCli._.extend.exit (/home/travis/build/Azure/azure-xplat-cli/lib/cli.js:162:10)
      at /home/travis/build/Azure/azure-xplat-cli/lib/cli.js:275:18
      at Object.exports.onError (/home/travis/build/Azure/azure-xplat-cli/lib/util/telemetry.js:271:5)
      at callback (/home/travis/build/Azure/azure-xplat-cli/lib/cli.js:265:21)
      at ___ (/home/travis/build/Azure/azure-xplat-cli/node_modules/streamline/lib/callbacks/runtime.js:108:14)
      at ___ (/home/travis/build/Azure/azure-xplat-cli/node_modules/streamline/lib/callbacks/runtime.js:108:14)
      at ___ (/home/travis/build/Azure/azure-xplat-cli/node_modules/streamline/lib/callbacks/runtime.js:108:14)
      at ___ (/home/travis/build/Azure/azure-xplat-cli/lib/commands/arm/vm/virtualMachine._js:718:17)
      at __tryCatch (/home/travis/build/Azure/azure-xplat-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)
      at ___ (/home/travis/build/Azure/azure-xplat-cli/lib/commands/arm/vm/virtualMachine._js:714:13)
      at __$getVMSizesByLocationName__16 (/home/travis/build/Azure/azure-xplat-cli/lib/commands/arm/vm/virtualMachine._js:711:15)
      at __tryCatch (/home/travis/build/Azure/azure-xplat-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)
      at ___ (/home/travis/build/Azure/azure-xplat-cli/lib/commands/arm/vm/virtualMachine._js:709:13)
      at ___ (/home/travis/build/Azure/azure-xplat-cli/lib/commands/arm/vm/virtualMachine._js:713:13)
      at ___ (/home/travis/build/Azure/azure-xplat-cli/node_modules/streamline/lib/callbacks/runtime.js:108:14)
      at /home/travis/build/Azure/azure-xplat-cli/node_modules/azure-arm-compute/lib/operations/virtualMachineSizes.js:152:14
      at retryCallback (/home/travis/build/Azure/azure-xplat-cli/node_modules/ms-rest/lib/filters/exponentialRetryPolicyFilter.js:140:9)
      at handleRedirect (/home/travis/build/Azure/azure-xplat-cli/node_modules/ms-rest/lib/filters/redirectFilter.js:36:9)
      at /home/travis/build/Azure/azure-xplat-cli/lib/util/utils.js:605:7
      at handleRedirect (/home/travis/build/Azure/azure-xplat-cli/lib/util/utils.js:582:9)
      at /home/travis/build/Azure/azure-xplat-cli/lib/util/logging.js:339:7
      at Request._callback (/home/travis/build/Azure/azure-xplat-cli/node_modules/ms-rest/lib/requestPipeline.js:125:16)
      at Request.self.callback (/home/travis/build/Azure/azure-xplat-cli/node_modules/request/request.js:187:22)
      at emitTwo (events.js:87:13)
      at Request.emit (events.js:172:7)
      at Request.<anonymous> (/home/travis/build/Azure/azure-xplat-cli/node_modules/request/request.js:1044:10)
      at emitOne (events.js:82:20)
      at Request.emit (events.js:169:7)
      at IncomingMessage.<anonymous> (/home/travis/build/Azure/azure-xplat-cli/node_modules/request/request.js:965:12)
      at emitNone (events.js:72:20)
      at IncomingMessage.emit (events.js:166:7)
      at endReadableNT (_stream_readable.js:923:12)
      at nextTickCallbackWith2Args (node.js:458:9)
      at process._tickCallback (node.js:372:17)
~~~

**Comment by balajikris** [comment]
beats me how updating OS versions could cause command failures in tests 😕 @amarzavery : any hints here? @szarkos 's change does not touch the product code at all, yet it leads to test failures. we looked but do not understand why this would happen. checking if you have any insights here.

**Comment by ejarvi** [comment]
I hit something similar recently in pull request [3502](https://github.com/Azure/azure-xplat-cli/pull/3502).

It is possible that the _azure-arm-network_ npm package in your local environment is out of date.  If so, the mock recordings that your local environment (on the older package) will generate are going to be incompatible with what the CI environment (on the newer package) requires.  

Make sure that your local environment is using the same exact package.json file currently in use in the azure/azure-xplat-cli dev branch (as of this post it is "azure-arm-network": "0.18.0").  If this file is out of sync with the upstream dev branch, then the dependencies it references may also be out of sync. The command `npm outdated` may be also be useful to check what version of azure-arm-network you actually have installed with what is required in the upstream package.json file.

Once all packages are in sync and updated, re-record the tests and submit, and the CI should pass.

**Comment by balajikris** [comment]
closing stale PR. as @ejarvi mentions above, issues do arise if your fork is out of date with the upstream. Instead of fixing this, please open a new PR

**Pull request closed without merging**
