### PR TITLE
bugfix: set endpoint status in Traffic manager didn't work correctly.

### PR DESCRIPTION
**Pull request by levaly**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@levaly__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by romangromov** [comment]
Let me verify this fix at first

**Comment by romangromov** [comment]
@levaly is there any opened issue for this?

**Comment by levaly** [comment]
Not that I am aware of, I came across the problem while trying to use that option.

**Comment by romangromov** [comment]
@levaly the same issue for `endpoint set`, will fix, thanks for contributing

**Pull request merged**
