### PR TITLE
Servicefabric fix update service command

### PR DESCRIPTION
**Pull request by msjeffreychen**
The content to be added to Changelog is as follows:
* fix update service command, instanceCount would not be udpated
* 
*

### CODE REVIEW

**Comment by balajikris** [comment]
is there a bug number that this addresses?

**Comment by msjeffreychen** [comment]
No, there is an email thread about this problem. If you would like, I could create a bug.

**Comment by balajikris** [comment]
Ah, I just asked so I could get context to review the code. Could you please forward me the context or create a bug on this repo? Either one is fine with me, I'd like to understand the problem before looking at the fix :)
Thank you.

**Comment by msjeffreychen** [comment]
Forwarded the email thread.

**Comment by balajikris** [comment]
Thanks, Change looks alright to me. If its possible to add tests for this case, that'd be nice. If not, I'm not too concerned. Thanks.

**Comment by msjeffreychen** [comment]
Please merge for us. Thanks.

**Pull request merged**
