### PR TITLE
ARM: 'network nsg rule create' added support for port range

### PR DESCRIPTION
**Pull request by romangromov**
This PR contains minor fix for issue https://github.com/Azure/azure-xplat-cli/issues/2238 + refactoring.

Please close this PR https://github.com/Azure/azure-xplat-cli/pull/2239 as duplicate.

### CODE REVIEW

**Comment by tung-jin-chew-hp** [comment]
Thanks, closed #2239 . Noticed a typo, the rename of 'params' to 'optioins' probably meant it to be 'options'.

**Comment by romangromov** [comment]
@tung-jin-chew-hp thanks, typo fixed

**Comment by yugangw-msft** [comment]
@romangromov,currently the github integration with travis CI is broken. 
Could you take a look at the CI log and fix the failure: https://travis-ci.org/Azure/azure-xplat-cli/builds/88762114

**Comment by romangromov** [comment]
@yugangw-msft oh,  I see, will fix. Please fix Travis asap...

**Comment by romangromov** [comment]
@yugangw-msft Travis fixed, we should be good here. Can we include this fix in `0.9.11`?

**Pull request merged**
