### PR TITLE
Fixed issue in app gateway show command

### PR DESCRIPTION
**Pull request by MikhailTryakhov**
The content to be added to Changelog is as follows:
* Fixed issue https://github.com/Azure/azure-xplat-cli/issues/3347

### CODE REVIEW

**Comment by balajikris** [comment]
No tests? The test suite clearly passes with or without the change, would be nice to add or modify a test to run through this codepath.

**Comment by MikhailTryakhov** [comment]
@balajikris thanks for your comments
Tests improved

**Comment by balajikris** [comment]
@MikhailTryakhov : I'm slightly confused - you seem to have closed this PR without merging. The related bug (3347) seems to have been closed as well and it points to this PR.  I see you have 2 new PRs open, but they seem to address different bugs and not 3347. Can you please explain?

**Comment by MikhailTryakhov** [comment]
@balajikris terribly sorry, made this accidently :) 
Can

**Pull request merged**
