### PR TITLE
URGENT!!! Traffic Manager improved by geo mappings, new SDK API

### PR DESCRIPTION
**Pull request by MikhailTryakhov**
The content to be added to Changelog is as follows:
* added api-version=2017-03-01
* Added geo mapping for endpoints

### CODE REVIEW

**Comment by MikhailTryakhov** [comment]
Hi @balajikris we have the same issue with all CLI tests in Travis - logs are too long because of deprecated lib in few commands block.
can you please help us to find guys who work on such command blocks?

**Comment by balajikris** [comment]
Hey @MikhailTryakhov - I do not have any context on who worked on commands. If I were you, I'd start looking at git history to understand who changed code.
Is that what you are looking for? If not, I'm sorry I didn't understand the issue correctly. feel free to email me and @amarzavery at our microsoft id, explaining the problem and what is that you need help with and we'll be happy to help.

**Comment by MikhailTryakhov** [comment]
@balajikris @amarzavery this PR is correct, the only problem is because of one of the libs are outdated and would be removed
Such improvements are correct and useful. Can we review it as an exception to merge so important updates? That's really long job between our team and we must have it in public this release

**Comment by amarzavery** [comment]
@MikhailTryakhov  - The CI is failing for traffic manager tests https://travis-ci.org/Azure/azure-xplat-cli/builds/215068827#L1570.

Please pull from upstream dev.

**Comment by MikhailTryakhov** [comment]
Hi @amarzavery thanks a lot for your help!
I've fixed tests magic issue so it can be published in release (I hope)

**Pull request merged**
