### PR TITLE
PR to address bug fixes for IAAS related issues

### PR DESCRIPTION
**Pull request by babumuralidharan**
Following are the issues that would be addressed with this PR.

https://github.com/Azure/azure-xplat-cli/issues/1416

https://github.com/Azure/azure-xplat-cli/issues/1500

https://github.com/Azure/azure-xplat-cli/issues/1516

https://github.com/Azure/azure-xplat-cli/issues/1554

https://github.com/Azure/azure-xplat-cli/issues/1565

https://github.com/Azure/azure-xplat-cli/issues/1566

https://github.com/Azure/azure-xplat-cli/issues/1569

https://github.com/Azure/azure-xplat-cli/issues/1575

https://github.com/Azure/azure-xplat-cli/issues/1583

https://github.com/Azure/azure-xplat-cli/issues/1589

https://github.com/Azure/azure-xplat-cli/issues/1594

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@babumuralidharan__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (v-bamura). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by amarzavery** [comment]
babumuralidharan - Can you please update ChangeLog.txt for the upcoming version 0.8.15 ?

**Comment by babumuralidharan** [comment]
@amarzavery Updated the changelog for 0.8.15 which includes the PR changes

**Comment by amarzavery** [comment]
@babumuralidharan - thank you. will merge the PR.

**Pull request merged**
