### PR TITLE
Add server farm option to site create and fix site repository branch

### PR DESCRIPTION
**Pull request by alexlau811**
This adds the option to choose server farm during web site creation. 

And sorry I am new to pull request in Github. Accidentally pushed also another fix with `site repository branch`.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexlau811__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by NaveenGoli** [comment]
No tests added?

**Comment by hovsepm** [comment]
Please pull from upstream and resolve conflicts.

**Comment by amarzavery** [comment]
@alexlau811 - Please re-record the current tests. The CI https://travis-ci.org/Azure/azure-xplat-cli/jobs/68304271  is failing because of this change.

Here is the link to documentation https://github.com/Azure/azure-xplat-cli/blob/dev/Documentation/README.md#azure-xplat-cli-documentation

**Comment by yugangw-msft** [comment]
Please reopen when you have addressed the review feedback

**Pull request closed without merging**
