### PR TITLE
[batch-beta-dev] Merge from dev + user-agent

### PR DESCRIPTION
**Pull request by annatisch**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@annatisch__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (antisch). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by annatisch** [comment]
@amarzavery - do you happen to have any ideas as to why the new user-agent telemetry tests would be failing? Three of them have the same issue in that the returned object has no attribute 'commandName'.
This is happening locally for me as well.
Is there any particular update or configuration I've missed? This PR should include the latest from dev.

**Comment by annatisch** [comment]
@Vasu1105  - we're seeing some failures in vm extension Chef extension tests and wondering if you could help us diagnose it.

Here's the travis log:
https://s3.amazonaws.com/archive.travis-ci.org/jobs/189647274/log.txt

The summary of the  errors are:
'1) cli vm extension: Set Chef extension should pass'

'Uncaught Error: Nock: No match for HTTP request GET /e00d2b3f-3b94-4dfc-ae8e-ca34c8ba1a99/services/images/03f55de797f546a1b29d1b8d66be687a__Team-Foundation-Server-2013-Update4-WS2012R2 '


'2) cli vm extension: Set Chef extensions with json attributes'

'Uncaught AssertionError: expected 1 to be 0'

Any help would be appreciated :)

**Comment by annatisch** [comment]
@amarzavery  - do you have any thoughts on these vm extension Chef tests?

**Pull request merged**
