### PR TITLE
Sql apiapp params

### PR DESCRIPTION
**Pull request by christav**
Update to parameter building logic for deploying apiapps to handle a corner case.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@christav__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (ctavares). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by amarzavery** [comment]
@christav - This LGTM :). Can you also update the Changelog? This makes our life easier.

**Comment by christav** [comment]
@amarzavery - Can I do that on Monday? There's generally a ton of merge conflicts with the changelog and I want to go home. :-)

**Comment by amarzavery** [comment]
@christav - Sure Sir, no worries. You can def do this on Monday. Have a great weekend :)

**Comment by christav** [comment]
@amarzavery Changelog has been updated. Could you please merge once travis goes green again?

**Pull request merged**
