### PR TITLE
AzureCP PR : VM/SS Image Aliases

### PR DESCRIPTION
**Pull request by huangpf**
The content to be added to Changelog is as follows:
* VM/SS Image Aliases

### CODE REVIEW

**Comment by huangpf** [comment]
@amarzavery @haocs @sauryadas Could you please help review? Thanks.

**Comment by huangpf** [comment]
Tests on Node 0.10 failed and pass on other 2 versions: https://travis-ci.org/Azure/azure-xplat-cli/jobs/125636751

Could you please help take a look? @amarzavery @haocs Thanks.

**Comment by haocs** [comment]
@huangpf - seems all failures caused by ```JSON.parse```
@amarzavery any thoughts?

**Comment by huangpf** [comment]
@haocs It's related to the ```sync-request``` package which doesn't work with ```node 0.10```.

I had turned that part into offline mode, so hopefully the tests shall pass.

**Pull request merged**
