### PR TITLE
Fix port range validation to allow dash-delimited port range

### PR DESCRIPTION
**Pull request by tung-jin-chew-hp**
Proposed fix for #2238 , works for me with both single ports and ranges.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@tung-jin-chew-hp__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by yugangw-msft** [comment]
@romangromov , please take a look.

**Comment by romangromov** [comment]
@yugangw-msft will re-work proposed fix a little bit, this PR can be closed, will send another one

**Comment by tung-jin-chew-hp** [comment]
Closing, fixed by romangromov accompanied by refactor in #2253

**Pull request closed without merging**
