### PR TITLE
Add batch cli for mangement and service operations.

### PR DESCRIPTION
**Pull request by xingwu1**
The content to be added to Changelog is as follows:
* 
*  Add batch management and service commands
*

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@xingwu1__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (xingwu). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by jasper-schneider** [comment]
So the test fails because it can't find a request in the recordings, but the recording files are included in the PR, and "node .\scripts\unit.js <test list>" passes on my machine.  Is there something extra we need to do in order to ensure that the tests can find the right recordings in the travis job?

Uncaught Error: Nock: No match for HTTP request PUT /subscriptions/46241355-bb95-46a9-ba6c-42b554d71925/resourceGroups/armclibatchgroup2809/providers/Microsoft.Batch/batchAccounts/armclibatch6301?api-version=2015-12-01 {"location":"westus"}

**Comment by jasper-schneider** [comment]
Disregard my earlier comment, Xing fixed things up and tests are passing now.

**Comment by amarzavery** [comment]
@jasper-schneider - Resolve conflicts

**Comment by xingwu1** [comment]
@amarzavery Rebase to latest check in.

**Pull request merged**
