### PR TITLE
fix issue in quick-create of user image (#3499)

### PR DESCRIPTION
**Pull request by ejarvi**
- Fixes issue of not being able to quick create a VM from a user image ( [#3499](https://github.com/Azure/azure-xplat-cli/issues/3499) ) 
- Adds optional --storage-account-name parameter to **vm quick-create** to support this 
- Includes unit tests for the scenario

### CODE REVIEW

**Comment by ejarvi** [comment]
unit tests did not integrate properly, investigating...

**Comment by ejarvi** [comment]
re-recording unit tests to bring them up to date with the most recent API version header

**Comment by huangpf** [comment]
LGTM, not sure why the CI tests fail.

**Comment by huangpf** [comment]
@amarzavery @balajikris

**Comment by ejarvi** [comment]
I think my local environment must be different than the CI test environment in some way.  

The error message from CI indicates that in that environment it is looking for a recorded URL that ends in **api-version=2016-04-30-preview** but can't find it because the recordings all end in **api-version=2016-03-30**.

In my own environment, when I launch  `npm run unit-arm` within my own environment these tests all pass.   But when they move to CI and CI generates that different version header than what my recordings used, the tests fail. 

_Here is the error output from the CI system:_

  1) arm compute vm quick create with non-existing group should pass:
     Uncaught Error: Nock: No match for HTTP request GET /subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Compute/locations/eastus/vmSizes?**api-version=2016-04-30-preview** 
      at RequestOverrider.end (/home/travis/build/Azure/azure-xplat-cli/node_modules/nock/lib/request_overrider.js:159:13)
      at OverridenClientRequest.RequestOverrider.req.end (/home/travis/build/Azure/azure-xplat-cli/node_modules/nock/lib/request_overrider.js:104:7)
      at Request.end (/home/travis/build/Azure/azure-xplat-cli/node_modules/request/request.js:1397:14)
      at end (/home/travis/build/Azure/azure-xplat-cli/node_modules/request/request.js:567:14)
      at Immediate._onImmediate (/home/travis/build/Azure/azure-xplat-cli/node_modules/request/request.js:581:7)
      at processImmediate [as _immediateCallback] (timers.js:396:17)

_Here is a snippet of the nock recording that I do have in place for that test:_
-  .get('/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Compute/locations/eastus/vmSizes?**api-version=2016-03-30**')
  .reply(200, "{\r\n  \"value\": [\r\n    {\r\n      \"name\": \"Standard_DS1_v2\",\r\n     ...

**Comment by huangpf** [comment]
@ejarvi 
There is a major release last week in CLI that changes the API version. I guess your package azure-arm-compute in node_modules didn't get upgrade properly.

Try delete them and redo 'npm install'

**Comment by ejarvi** [comment]
@huangpf 
Yes -- that package was indeed out of date on my end.  I've updated it to the most recent and I am in the process of re-recording the tests now.

**Comment by ejarvi** [comment]
@huangpf @amarzavery @balajikris
Thanks for your help, the newly recorded tests have now passed the CI check.

**Comment by huangpf** [comment]
LGTM.

**Comment by ejarvi** [comment]
@huangpf @amarzavery @balajikris
Please merge

**Comment by balajikris** [comment]
hey @ejarvi - I think you'll have to regenerate plugins*.json for this change?

**Comment by ejarvi** [comment]
Good catch - thanks for mentioning this.  I also found a conflict in the short code when I was looking there.


I have submitted a new PR with plugins*.json change and updated the tests to reflect this and give some better coverage:


https://github.com/Azure/azure-xplat-cli/pull/3508

regenerate plugins.arm.json for quick-create params by ejarvi · Pull Request #3508 · Azure/azure-xplat-cli · GitHub<https://github.com/Azure/azure-xplat-cli/pull/3508>
github.com
azure-xplat-cli - Microsoft Azure Cross Platform Command Line

**Pull request merged**
