### PR TITLE
Added user-agent header via environment variable.

### PR DESCRIPTION
**Pull request by haocs**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@haocs__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by haocs** [comment]
@yugangw-msft , @chrisrpatterson - Please help review. This PR is to support 'set AzureCLI user agent header via environment'.

**Comment by yugangw-msft** [comment]
:shipit:

**Comment by chrisrpatterson** [comment]
Looks good to me.

**Pull request merged**
