### PR TITLE
ARM network: added support for IPv6, multiple ip-configs for NIC

### PR DESCRIPTION
**Pull request by romangromov**
The content to be added to Changelog is as follows:
* using new api version for networking commands: 2016-03-30  (azure-arm-network: 0.13.2);
* 'network nic show': added InternalDomainNameSuffix propert;
* 'network public-ip create': added --ip-version option to specify ip version of IPv4 or IPv6;
* 'network nic ip-config' commands added to manage multiple ip configurations inside nic;
* **Breaking change:** 'network nic set' no longer has options to modify ip configuration, use 'network nic ip-config' commands instead;
* **Breaking change:** 'network nic address-pool/inbound-nat-rule' commands now are subcategories of 'network nic ip-config address-pool/inbound-nat-rule';
* **Breaking change:**: 'network nic ip-config address-pool/inbound-nat-rule'' option -n,--name was renamed to -c, --nic-name for consistency;

Note: IPv6 feature not published to Azure PROD, so it's required to contact Azure Networking team to enable IPv6 as well as NIC multiple ip configurations feature for used subscription - please contact derajen@exchange.microsoft.com

Also:
* test cases update;
* nocks updated;

Adding @DeepakRajendranMsft for review, approve confirmation

### CODE REVIEW

**Comment by DeepakRajendranMsft** [comment]
LGTM

**Comment by romangromov** [comment]
@DeepakRajendranMsft 
actually the ip-config commands below always `add/remove`, but in Xplat-CLI, we have to follow `CRUD` naming convention – that is requirement from @amarzavery  and @yugangw-msft and also XPlat docs [here](https://github.com/Azure/azure-xplat-cli/blob/dev/Documentation/Writing-Cmd.md#command-design-guidelines) for the reference

**Comment by romangromov** [comment]
@DeepakRajendranMsft 
actually the ip-config commands below always `add/remove`, but in Xplat-CLI, we have to follow `CRUD` naming convention – that is requirement from @amarzavery  and @yugangw-msft and also XPlat docs [here](https://github.com/Azure/azure-xplat-cli/blob/dev/Documentation/Writing-Cmd.md#command-design-guidelines) for the reference

**Comment by romangromov** [comment]
@amarzavery @yugangw-msft we are good to go - please merge this PR

**Comment by romangromov** [comment]
FYI: @DeepakRajendranMsft PR merged

**Pull request merged**
