### PR TITLE
Xplat CLI performance improvement

### PR DESCRIPTION
**Pull request by ljhljh235**
command help load < 0.25s
command autocomplete ~< 0.1s

on a mac mini.

### CODE REVIEW

**Comment by yugangw-msft** [comment]
This is amazing. 
The "final3" branch from my fork has newer work of splitting out the big "utils.js" file which will save another 200 ms from command loading. Let us merge tomorrow and cut out a installer for David to test

**Comment by yugangw-msft** [comment]
Closing this as #1832 contains more fix

**Comment by devigned** [comment]
@yugangw-msft and @ljhljh235 .25 second auto-complete is the awesome! Great job! :+1:

**Comment by kmouss** [comment]
Awesome!

**Comment by rgardler** [comment]
Impressive!

**Pull request closed without merging**
