### PR TITLE
[not for merge] Fix 'ConsoleScreenshotBlobUri' should not be set

### PR DESCRIPTION
**Pull request by EvgenyAgafonchikov**
* This fixes `cli vm Create a VM with static ip address: VM Create-from a file and assert the static ip` test failure in non-playback mode
* Fix code style

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@EvgenyAgafonchikov__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by huangpf** [comment]
It seems only test files are updated, and may I know where is the fix?

**Comment by MikhailTryakhov** [comment]
Hi @huangpf, 
we're working on fixes in tests (Live/Recording mode). 
Currently our tests on Travis uses only Playback mode, but fixes in Live/Recording are needed - many of them actually do not work anymore.
In this case Evgeny works on issue like [#2926](https://github.com/Azure/azure-xplat-cli/issues/2926) - assume it was fixed in code but not in tests

**Comment by MikhailTryakhov** [comment]
Close until it would be fixed

**Pull request closed without merging**
