### PR TITLE
Replaced ARM NSG by generated code

### PR DESCRIPTION
**Pull request by MikhailTryakhov**

### CODE REVIEW

**Comment by MikhailTryakhov** [comment]
Hi @balajikris 
this PR is ready for review too

**Comment by balajikris** [comment]
@MikhailTryakhov - pls fix merge conflicts here

**Comment by MikhailTryakhov** [comment]
@balajikris, thank you, updated

**Comment by balajikris** [comment]
@MikhailTryakhov : please fix conflicts again, It became out of date soon as I merged one of your other PRs. This is expected.

**Pull request merged**
